apiVersion: v1
kind: Service
metadata:
  name: test-elasticapm-service
spec:
  type: NodePort
  selector:
    app: elasticapm
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 32525
